name: Build Master

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Gradle Caches
      id: cache-gradle-caches
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-${{hashFiles('**/*.gradle')}}
        path: |
          ~/.gradle/caches
    - name: Cache Gradle Wrapper
      id: cache-gradle-wrapper
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        path: |
          ~/.gradle/wrapper
    - uses: gradle/wrapper-validation-action@v1
      name: Validate Gradle Wrapper

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Install font
      run: |
        export PROJECT_ROOT=$PWD
        cd /tmp/
        tar xzvf $PROJECT_ROOT/stylesheet/nflx/font.tgz
        mkdir -p ~/.fonts
        cp -r package/fonts/* ~/.fonts/
        fc-cache -f -v

    - name: Build with Gradle
      run: |
        ./gradlew build

    - name: Deploy Github Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: pages/build/staging
