name: Build PR

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Gradle Caches
      id: cache-gradle-caches
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-${{hashFiles('**/*.gradle')}}
        path: |
          ~/.gradle/caches
    - name: Cache Gradle Wrapper
      id: cache-gradle-wrapper
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        path: |
          ~/.gradle/wrapper
    - uses: gradle/wrapper-validation-action@v1
      name: Validate Gradle Wrapper

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: '14.17.0'

    - name: Install vega
      run: |
        npm install -g vega
        npm install -g vega-lite
        npm install -g vega-cli
        npm install -g vega-embed

    - name: Install font
      run: |
        export PROJECT_ROOT=$PWD
        cd /tmp/
        tar xzvf $PROJECT_ROOT/stylesheet/nflx/font.tgz
        mkdir -p ~/.local/share/fonts
        cp -r package/fonts/*.ttf ~/.local/share/fonts
        chmod 755 ~/.local/share/fonts
        chmod 644 ~/.local/share/fonts/*.ttf
        fc-cache -f -v

    - name: Build with Gradle
      run: |
        ./gradlew build --scan
